# Run regularly to update dependencies and perform similar maintenance
maintain: 
    find . -name "*.ts" | xargs udd

# Run unit tests (docs/public, which are generated by tests, will be deleted first)
test:
    deno test -A --unstable --fail-fast